### PR TITLE
drivers: led: lp5569: implement write_channels api

### PR DESCRIPTION
**Pull request by Emil-Juhl**
See commits.

Submitted for upstream: https://github.com/zephyrproject-rtos/zephyr/pull/81497

### CODE REVIEW

**Comment by Emil-Juhl** [comment]
Since we are far far behind upstream main, the first commit didn't cherry-pick cleanly. But this is merely due to formatting.

**Review by DmtKats — DISMISSED** [review]
Lets wait a bit for the upstream review. If you really need this now we can just merge

**Comment by Emil-Juhl** [comment]
Upstream merged with minor changes - I think I'll just backport the relevant patches; maybe including the older stuff that reformatted code etc.

**Comment by Emil-Juhl** [comment]
@dkarnikis @DmtKats I now reverted our two bespoke patches for the lp5569 and cherry-picked the entire range of patches from upstream (up until the point of lp5569 write_channels).

**Review by DmtKats — APPROVED** [review]

**Pull request merged**
